### ISSUE TITLE
Simple_ota exempla not working - can't find protocol_examples_common/include dir

### ISSUE THREAD

**Issue by GKFernandes** [maxgerhardt/pio-espidf-simple-ota-example#1]
Hi @maxgerhardt ,

I was trying to perform the first steps of this example by running pio run -t menuconfig after cloning the repo, and it seems it's looking for an unknown folder:

![ex_pio_ota1](https://user-images.githubusercontent.com/87312710/126369915-423a15b1-9df7-4b57-b840-e40dc7a3a244.png)

Any clues on what could be the issue?

Thanks in advance!

**Comment by maxgerhardt** [comment]
Can you remove the entire line 

https://github.com/maxgerhardt/pio-espidf-simple-ota-example/blob/f34670f8db43dcec9b84d6a343b0303402f89989/components/protocol_examples_common/CMakeLists.txt#L2

and retry?

**Comment by maxgerhardt** [comment]
If that does not work, please change 

https://github.com/maxgerhardt/pio-espidf-simple-ota-example/blob/f34670f8db43dcec9b84d6a343b0303402f89989/platformio.ini#L12

to

```ini
platform = espressif32@3.2.1
```

because at the time of creation, it was built on ESP-IDF 4.2, not ESP-IDF 4.3 which is [in the latest platform version](https://github.com/platformio/platform-espressif32/releases). The project may be incompatible with ESP-IDF 4.3.

**Comment by GKFernandes** [comment]
Hello there @maxgerhardt ,

Thanks for the reply.

So, I tried first deleting the INCLUDE_DIRS "include" line, and then at the IDF_PATH/tools/cmake/component.cmake, it could not find the sources to build the protocol_examples_common target.

![simple_ota_01](https://user-images.githubusercontent.com/87312710/126483560-927b2d19-e551-46d1-90dd-0ab723f017b5.png)


Then I tried switching to the platform=espressif32@3.2.1 and it can't find the project.cmake load file.

![simple_ota_02](https://user-images.githubusercontent.com/87312710/126483359-21cf1b5b-aea9-435d-b26c-e5cc9cb5c1cd.png)

Maybe if I try just changing the ESP-IDF version without deleting the INCLUDE_DIRS line?

Edit1: I noticed that connect.c and stdinout.c are also not in the folder, should they be there?

Thanks,

**Comment by maxgerhardt** [comment]
Does 

```
platform = espressif32@3.2.0
```

work? Also, if there's a config failure, delete the `.pio` folder of the project, that will make it reconfigure it from scratch.

**Comment by GKFernandes** [comment]
Unfortunately platform=espressif32@3.2.0 does not work.

I've tried it both ways, leaving the project 'as is' and deleting the INCLUDE_DIRS line on the CMakeLists file. I made sure I was deleting the .pio folder whenever I deleted the line or changed the ESP-IDF version

I get this error:

![simple_ota_03](https://user-images.githubusercontent.com/87312710/126494966-54bcaec9-2319-47ab-b2f1-c84eec89b29e.png)

**Comment by maxgerhardt** [comment]
Okay the 
https://github.com/maxgerhardt/pio-espidf-simple-ota-example/blob/f34670f8db43dcec9b84d6a343b0303402f89989/components/protocol_examples_common/CMakeLists.txt#L1

is a problem when those files aren't there from https://github.com/espressif/esp-idf/tree/v4.2/examples/common_components/protocol_examples_common. I'll correct it.

**Comment by maxgerhardt** [comment]
I've updated the repo in the latest commit to work with the *latest* platform version. Please `git reset --hard && git pull` and retry.

```
Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)
------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (3.3.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-espidf 3.40300.0 (4.3.0)
 - tool-cmake 3.16.4
 - tool-esptoolpy 1.30100.210531 (3.1.0)
 - tool-idf 1.0.1
 - tool-mconf 1.4060000.20190628 (406.0.0)
 - tool-ninja 1.9.0
 - toolchain-esp32ulp 1.22851.191205 (2.28.51)
 - toolchain-xtensa32 2.80400.210114 (8.4.0)
..
Checking size .pio\build\esp32dev\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  10.1% (used 33248 bytes from 327680 bytes)
Flash: [========  ]  79.5% (used 834005 bytes from 1048576 bytes)
Building .pio\build\esp32dev\firmware.bin
esptool.py v3.1
Merged 1 ELF section
========== [SUCCESS] Took 62.45 seconds ==========
```

**Comment by GKFernandes** [comment]
Thank you for the quick reponse and fixes.

I've resetted the repo and updated it and the example seems to be working, it surely has compiled.

What I think is happening is that it is performing the OTA to the hello-world.bin and this new firmware does not know my Wi-Fi credentials to connect back again to Wi-Fi, so it's printing this quite funny log:

![simple_ota_04](https://user-images.githubusercontent.com/87312710/126507224-a4868d25-72ce-45c3-8fad-792db51e5d9a.png)

The HTTPS server output seems to show that the file have been transferred correctly:

![simple_ota_05](https://user-images.githubusercontent.com/87312710/126507419-c9990647-76f0-4bec-a314-ecfbbc5db468.png)

**Comment by maxgerhardt** [comment]
Ah yeah the `hello-world.bin` is a precompiled version for my WiFi name (without the creds though). You can grab the `.pio\build\esp32dev\firmware.bin` after you've built the firmware and copy it in the http_server_root as `hello-world.bin` -- should give you an infinite OTAA loop, with the updated firmware again updating itself.

Closing since the compilation issue is solved.
