### ISSUE TITLE
Build errors with latest versions

### ISSUE THREAD

**Issue by torntrousers** [maxgerhardt/pio-espidf-simple-ota-example#2]
Hello, this looks like the perfect example for what I'm looking for, but I can't get it to build successfully. I guess its on older versions and the current pio idf support is on framework-espidf @ 3.50001.0 (5.0.1) now.

Can you give any help?

**Comment by torntrousers** [comment]
Maybe that didn't have enough detail, so here is more:
The first problem is a compile error:
```
src/simple_ota_example.c: In function '_http_event_handler':
src/simple_ota_example.c:36:5: error: enumeration value 'HTTP_EVENT_REDIRECT' not handled in switch [-Werror=switch]
```
which is simply fixed with:
```
git diff src/simple_ota_example.c
diff --git a/src/simple_ota_example.c b/src/simple_ota_example.c
index c99def7..cfd3a05 100644
--- a/src/simple_ota_example.c
+++ b/src/simple_ota_example.c
@@ -55,6 +55,9 @@ esp_err_t _http_event_handler(esp_http_client_event_t *evt)
     case HTTP_EVENT_DISCONNECTED:
         ESP_LOGD(TAG, "HTTP_EVENT_DISCONNECTED");
         break;
+    case HTTP_EVENT_REDIRECT:^M
+        ESP_LOGD(TAG, "HTTP_EVENT_DISCONNECTED");^M
+        break;^M
     }
     return ESP_OK;
 }
```
but then it fails with:
```
Compiling .pio\build\esp32dev\protocomm\src\common\protocomm.o
components\protocol_examples_common\stdin_out.c:12:10: fatal error: esp_vfs_dev.h: No such file or directory

*********************************************************************
* Looking for esp_vfs_dev.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_vfs_dev.h"
* Web  > https://registry.platformio.org/search?q=header:esp_vfs_dev.h
*
*********************************************************************

   12 | #include "esp_vfs_dev.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\esp32dev\components\protocol_examples_common\stdin_out.o] Error 1
components\protocol_examples_common\connect.c:14:10: fatal error: esp_wifi.h: No such file or directory

******************************************************************
```
I did then go find ```components\protocol_examples_common``` and copy that directory into here which caused even more harder to fix errors.

Is there any chance you could help get this example running on the latest IDF code?

**Comment by maxgerhardt** [comment]
The https://github.com/maxgerhardt/pio-espidf-simple-ota-example/tree/main/components/protocol_examples_common folder is very likely outdated. Delete that and put in the new one from https://github.com/espressif/esp-idf/tree/v5.0/examples/common_components/protocol_examples_common

**Comment by torntrousers** [comment]
thank you so much, that does fix it along with an update to CMakeLists.txt to add ```REQUIRES esp_wifi```, and now it all builds cleanly.
Any interest in a PR for this or its fairly straight forward i guess for you to fix sometime.

**Comment by maxgerhardt** [comment]
Can you do a PR into here? CI will be usefull here.

**Comment by torntrousers** [comment]
Thanks!
